---
settings:
  name: NetApp Ransomware Resilience
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    release_notes_repo: console-relnotes
  rss_page: whats-new.html
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: NetApp Ransomware Resilienceドキュメント
    url: "/index.html"
  - title: リリース ノート
    entries:
    - title: ランサムウェア耐性の新機能
      url: "/whats-new.html"
    - title: 既知の制限事項
      url: "/rp-reference-limitations.html"
  - title: 始めましょう
    entries:
    - title: ランサムウェア耐性について学ぶ
      url: "/concept-ransomware-resilience.html"
    - title: 前提条件
      url: "/rp-start-prerequisites.html"
    - title: クイック スタート
      url: "/rp-start-quick-start.html"
    - title: ランサムウェア耐性を設定する
      url: "/rp-start-setup.html"
    - title: ライセンスの設定
      url: "/rp-start-licenses.html"
    - title: ワークロードを発見する
      url: "/rp-start-discover.html"
  - title: ランサムウェア耐性を活用する
    entries:
    - title: ランサムウェア耐性にアクセス
      url: "/rp-start-login.html"
    - title: ワークロードの健全性を表示する
      url: "/rp-use-dashboard.html"
    - title: 保護と検出
      entries:
      - title: 保護の確認
        url: "/task-review-protection.html"
      - title: バックアップ先を設定する
        url: "/task-backup-destination.html"
      - title: ワークロードを保護する
        url: "/rp-use-protect.html"
      - title: ユーザーアクティビティ検出を設定する
        entries:
        - title: ユーザーアクティビティ検出について学ぶ
          url: "/concept-user-behavior.html"
        - title: ユーザアクティビティ検出要件
          url: "/reference-user-activity-requirements.html"
        - title: エージェントとコレクターを設定する
          url: "/suspicious-user-activity.html"
      - title: 保護グループの管理
        url: "/task-protection-group.html"
      - title: 個人を特定できるデータをスキャンする
        url: "/task-classify.html"
    - title: 対応と回復
      entries:
      - title: 検出されたアラートに応答する
        url: "/rp-use-alert.html"
      - title: ランサムウェア攻撃からの回復
        url: "/rp-use-recover.html"
    - title: 準備訓練を実施する
      url: "/rp-start-simulate.html"
    - title: SIEMの設定
      url: "/task-siem.html"
    - title: レポートをダウンロード
      url: "/rp-use-reports.html"
  - section: support
  - title: FAQ
    url: "/rp-start-faq.html"
  - title: 法律上の表示
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
