---
sidebar: sidebar 
permalink: rp-reference-limitations.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: 既知の制限事項では、この製品リリースでサポートされていないプラットフォーム、デバイス、または機能が特定されます。 
---
= NetApp Ransomware Resilienceの既知の制限事項
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
今回のリリースでサポートされていない、または今回のリリースでは正常に機能しないプラットフォーム、デバイス、機能が記載されています。これらの制限事項をよく確認してください。



[[readiness-drill-reset-option-issue]]
== 準備訓練リセットオプションの問題

ランサムウェア攻撃対策ドリル用にONTAP 9.11.1 ボリュームを選択すると、Ransomware Resilience によってアラートが送信されます。  「ボリュームへのクローン」オプションを使用してデータを回復し、ドリルをリセットすると、リセット操作は失敗します。



[[amazon-fsx-for-netapp-ontap-limitations]]
== Amazon FSx for NetApp ONTAP の制限

Amazon FSx for ONTAPには以下の制限が適用されます：

* バックアップポリシーは Amazon FSx for ONTAP ではサポートされていません。この環境では、Amazon FSx バックアップを使用してバックアップ操作を実行してください。これらのワークロードは、Ransomware Resilience を使用して復元できます。
* 復元操作はスナップショットからのみ実行されます。




[[azure-netapp-files-limitations]]
== Azure NetApp Files の制限事項

Azure NetApp Files には以下の制限事項が適用されます：

* バックアップポリシーを使用したランサムウェア保護戦略は、Azure NetApp Files ではサポートされていません。代わりに、Azure NetApp Files バックアップを使用できます。
* レプリケーションを使用したランサムウェア保護戦略は Azure NetApp Files ではサポートされていません。
* Azure NetApp Files は FPolicy やユーザー行動検出をサポートしていません。Azure NetApp Files はエントロピーフォレンジックもサポートしていません。
* 保護戦略を選択するときは、スナップショットスケジュールがAzure NetApp Filesと互換性があることを確認してください。Azure NetApp Filesで利用できる最も頻繁なスナップショットスケジュールは1時間ごとです。
* Azure NetApp Files では、Azure NetApp Files API が自動操作をブロックするため、link:reference-soar.html["SOARプレイブック"]を使用しないことをお勧めします。
* 一部のイベントデータは、Azure NetApp Files 構成のlink:task-siem.html["SIEMレポート"]には含まれていません。




[[google-cloud-netapp-volumes-limitations]]
== Google Cloud NetApp Volumes の制限事項

Google Cloud NetApp Volumes には以下の制限事項が適用されます：

* 現在、Google Cloud NetApp Volumes ワークロードに適用できる保護戦略は、暗号化と FPolicy に基づくものに限られています。ユーザー行動保護戦略を適用することはできません。
* レプリケーションを使用した保護戦略は、現在 Google Cloud NetApp Volumes ではサポートされていません。




[[san-storage-limitations]]
== SANストレージの制限

SAN（ブロックストレージ）ワークロードには、以下の制限事項が適用されます。

* Ransomware ResilienceがSANワークロードに対して警告を生成する場合、それらの警告は高エントロピーのみに基づいています。
* SANワークロードは、link:task-custom-restore.html["カスタム復元"]を使用してのみリストアできます。SANワークロードでは、クリーンリストアは現在利用できません。




[[multi-admin-verification]]
== マルチ管理者認証

マルチ管理者認証は、ランサムウェア耐性または NetApp Console ではサポートされていません。link:https://docs.netapp.com/us-en/ontap/multi-admin-verify/["ONTAPのマルチ管理者検証"^] を設定している場合、保護機能を有効にしたり、準備訓練を実施したり、復元操作を実行したりすることはできません。これらの操作を試みる前に、マルチ管理者認証を無効にする必要があります。
