---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: 環境、ネットワーク アクセス、ログイン、Web ブラウザーのサポートを確認して、 NetApp Ransomware Resilienceを開始してください。 
---
= NetApp Ransomware Resilienceの前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
運用環境、ログイン、ネットワーク アクセス、Web ブラウザの準備状況を確認して、 NetApp Ransomware Resilienceを開始してください。

Ransomware Resilience を使用するには、次の前提条件を満たす必要があります。



== NetApp Console

* リソースを検出するための組織管理者権限を持つNetApp Consoleユーザー アカウント。
* オンプレミスのONTAPクラスターまたは AWS または Azure のCloud Volumes ONTAPに接続するアクティブなコンソールエージェントが少なくとも 1 つあるコンソール組織。
* コンソールエージェントには、 `cloudmanager-ransomware-protection`アクティブな状態のコンテナ。
* NetAppオンプレミスONTAPクラスターまたは AWS または Azure のCloud Volumes ONTAP を備えた少なくとも 1 つのコンソール システム。  Ransomware Resilience は、NAS (NFS および SMB) と SAN (iSCSI、FC、NVMe) の両方のプロトコルをサポートします。
+
** ONTAP OS バージョン 9.11.1 以降のONTAPまたはCloud Volumes ONTAPクラスターがサポートされています。
+

NOTE: SAN ワークロードは、 ONTAP 9.17.1 以降でのみサポートされます。

** オンプレミスのONTAPクラスターまたは AWS または Azure クラウドのCloud Volumes ONTAP がコンソールにまだオンボードされていない場合は、コンソール エージェントが必要です。
+
参照 https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["コンソールエージェントの設定方法を学ぶ"]そして https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["標準コンソール要件"^]。

+

NOTE: 単一のコンソール組織に複数のコンソール エージェントがある場合、Ransomware Resilience は、コンソール UI で現在選択されているエージェント以外のすべてのコンソール エージェントにわたってONTAPリソースをスキャンします。







== ONTAP 9.11.1以降

* オンプレミスのONTAPインスタンスでONTAP One ライセンスが有効になっています。
* 使用しているONTAPのバージョンに応じて、オンプレミスのONTAPインスタンスで有効化された、Ransomware Resilience によって使用されるNetApp Autonomous Ransomware Protection のライセンス。参照 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自律型ランサムウェア対策 - 概要"^]。
+

NOTE: Ransomware Resilience の一般リリースには、プレビュー リリースとは異なり、 NetApp Autonomous Ransomware Protection テクノロジーのライセンスが含まれています。参照 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自律型ランサムウェア対策 - 概要"^]詳細については。

+
ライセンスの詳細については、link:concept-ransomware-resilience.html["ランサムウェア耐性について学ぶ"] 。

* 保護構成（自律型ランサムウェア保護の有効化など）を適用するには、Ransomware Resilience にONTAPクラスターに対する管理者権限が必要です。  ONTAPクラスタは、 ONTAPクラスタ管理者のユーザー認証情報のみを使用してオンボードされている必要があります。
* ONTAPクラスタが非管理者ユーザの認証情報を使用してコンソールにすでにオンボードされている場合は、このページで説明されているように、 ONTAPクラスタにログインして、非管理者ユーザの権限を必要な権限で更新する必要があります。




== データのバックアップ用

* バックアップ ターゲットおよびアクセス権限セット用のNetApp StorageGRID、AWS S3、Azure Blob、または Google Cloud Platform のアカウント。
+
参照 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS、Azure、またはS3の権限リスト"^]詳細については。

* システムでNetApp Backup and Recovery を有効にする必要はありません。
+
Ransomware Resilience は、設定オプションを通じてバックアップの保存先を構成するのに役立ちます。見るlink:rp-use-settings.html["設定を構成する"] 。





== ONTAPシステムで管理者以外のユーザーの権限を更新する

特定のシステムの管理者以外のユーザー権限を更新する必要がある場合は、次の手順を実行します。

. コンソールにログインし、 ONTAPユーザー権限の更新が必要なシステムを探します。
. 詳細を表示するにはシステムを選択してください。
. ユーザー名を表示するには、[*追加情報を表示*] を選択します。
. admin ユーザーを使用してONTAPクラスタ CLI にログインします。
. そのユーザーの既存のロールを表示します。入力：
+
[listing]
----
security login show -user-or-group-name <username>
----
. ユーザーの役割を変更します。入力：
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. 使用するには、ランサムウェア耐性 UI に戻ります。

