---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: 環境、ネットワーク アクセス、ログイン、Web ブラウザーのサポートを確認して、 NetApp Ransomware Resilienceを開始してください。 
---
= NetApp Ransomware Resilienceの前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
NetApp Ransomware Resilienceの導入を確実に成功させるには、運用環境の準備状況、ネットワーク アクセス、およびWebブラウザを確認してください。

以下の要件を確認し、満たしていることを確認してください。



== サポートされているシステム

サポートされているシステムを使用していることを確認してください。

|===
| 環境 | プロトコル | サポート対象のバージョン 


| Amazon FSx for NetApp ONTAP* | CIFS、NFS、SAN | 該当なし 


| Azure NetApp Files | CIFSとNFS | 該当なし 


.2+| Cloud Volumes ONTAP for AWS | CIFSとNFS | 9.11.1以降 


| SAN（iSCSI および NVMe） | 9.17.1以降 


.2+| Google Cloud Platform 向けCloud Volumes ONTAP | CIFSとNFS | 9.11.1以降 


| SAN（iSCSI および NVMe） | 9.17.1以降 


.2+| Microsoft Azure 向けCloud Volumes ONTAP | CIFSとNFS | 9.12.1以降 


| SAN（iSCSI および NVMe） | 9.17.1以降 


.2+| ONTAP （オンプレミス） | CIFSとNFS | 9.11.1以降 


| SAN（iSCSI および NVMe） | 9.17.1以降 


| Google Cloud NetApp Volumes | CIFS、NFS、SAN（iSCSI および NVMe） | 該当なし 
|===
{アスタリスク} Amazon FSx for NetApp ONTAP は、 ARP/AI ではなく、Autonomous Ransomware Protection (ARP) を使用します。違いの詳細については、link:https://docs.netapp.com/us-en/ontap/anti-ransomware/#arp-ai["ARP/AI"^] 。


NOTE: Azure NetApp FilesまたはGoogle Cloud NetApp Volumesでは、ユーザーアクティビティ検出はサポートされていません。ユーザーアクティビティ検出のサポートの詳細については、link:reference-user-activity-requirements.html["ユーザアクティビティ検出要件"]を参照してください。



== NetApp Consoleの要件

NetApp Consoleの構成には次のものが必要です。

* リソースを検出するための組織管理者権限を持つNetApp Consoleユーザー アカウント。
* 少なくとも1つのアクティブなコンソールエージェントが接続しているコンソール組織とシステムlink:concept-ransomware-resilience.html#supported-backup-targets-systems-and-workload-data-sources["サポートされているシステム"]。
+
** オンプレミス ONTAP クラスタまたは Cloud Volumes ONTAP システムが NetApp Console で設定されていない場合は、link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["コンソールエージェントの設定方法を学ぶ"^]およびlink:https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["標準コンソール要件"^]を参照してください。
+

NOTE: 単一のコンソール組織に複数のコンソールエージェントがある場合、ランサムウェア耐性は、コンソールUIで現在選択されているエージェント以外の、すべてのコンソールエージェントにわたるONTAPリソースをスキャンします。



* コンソールエージェントには、 `cloudmanager-ransomware-protection`アクティブな状態のコンテナ。
* ONTAPまたはCloud Volumes ONTAPクラスタの場合、ランサムウェア耐性にはONTAPバージョン9.11.1以降が必要です。
+

NOTE: SAN ワークロードで Ransomware Resilience を使用するには、 ONTAP 9.17.1 以降を実行している必要があります。





== ONTAPの要件

* オンプレミスのONTAPインスタンスでONTAP One ライセンスが有効になっているONTAP 9.11.1 以降を実行している必要があります。  ONTAPサポートの詳細については、以下を参照してください。link:https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自律型ランサムウェア対策 - 概要"^] 。
* 保護構成（自律型ランサムウェア保護の有効化など）を適用するには、Ransomware Resilience にONTAPクラスターに対する管理者権限が必要です。ONTAPクラスタは、 ONTAPクラスタ管理者のユーザー認証情報のみを使用してオンボードされている必要があります。



NOTE: 管理者以外の資格情報を使用してONTAPクラスターをコンソールに接続している場合は、<<ONTAPシステムで管理者以外のユーザーの権限を更新する>>する必要があります。



== データのバックアップ

* 適切なアクセス権限が設定されたバックアップ ターゲット用のNetApp StorageGRID、AWS S3、Azure Blob、または Google Cloud Platform のアカウント。
+
参照 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS、Azure、またはS3の権限リスト"^]詳細については。




NOTE: link:task-backup-destination.html["Ransomware Resilienceでバックアップ先を設定する"]できます。ワークロードがNetApp Backup and Recoveryで保護されている場合、Ransomware Resilienceは、スナップショットやバックアップ先などの保護の詳細を自動的に認識します。Ransomware Resilienceを使用するために、Backup and Recoveryは必須ではありません。



== ユーザー行動検出の要件

NetApp Ransomware Resilienceがユーザーの行動に関するアラートを提供するには、ユーザーアクティビティエージェントを設定する必要があります。ユーザーアクティビティエージェントをインストールするには、システムがlink:reference-user-activity-requirements.html["要件"]を満たしていることを確認してください。



== クリーンリストアの前提条件

Ransomware Resilienceは、最適な復旧経路を見つけるためのガイド付き復旧プロセスを提供する、クリーンな復元機能を提供します。クリーンリストアを使用するには、link:task-clean-restore.html["前提条件を満たしていることを確認してください"]。



== ONTAPシステムで管理者以外のユーザーの権限を更新する

特定のシステムにおける管理者以外のユーザーの権限を更新する必要がある場合は、以下の手順に従ってください：

. コンソールにログインします。ダッシュボードで、ONTAP ユーザー権限を更新する必要があるシステムを特定します。
. システムを選択して詳細を表示します。
. ユーザー名を表示するには、[*追加情報を表示*] を選択します。
. 管理者ユーザーとしてONTAPクラスタ CLI にログインします。
. そのユーザーの既存のロールを表示します：
+
[listing]
----
security login show -user-or-group-name <username>
----
. ユーザーの役割を変更します。入力：
+
[listing]
----
security login modify -user-or-group-name <name> -application console|http|ontapi|ssh -authentication-method password -role admin
----
. Ransomware Resilience を使用するには、 NetApp Consoleに戻ります。

