---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: Ransomware Resilience を使用するには、いくつかの手順を実行して設定します。 
---
= NetApp Ransomware Resilienceを設定する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
バックアップ先の準備、前提条件の確認、NetApp Console およびコンソールエージェントの設定を行うことで、NetApp Ransomware Resilience をセットアップします。



[[prepare-the-backup-destination]]
== バックアップ先を準備する

次のいずれかのバックアップ先を準備します。

* NetAppStorageGRID
* Amazon Web Services
* Google Cloud Platform
* Microsoft Azure


バックアップ先自体でオプションを構成した後、後でNetApp Ransomware Resilienceでバックアップ先として構成します。NetApp Ransomware Resilienceにおけるバックアップ先の設定方法の詳細については、link:task-backup-destination.html["バックアップ先を設定する"]を参照してください。



[[prepare-storagegrid-to-become-a-backup-destination]]
=== StorageGRIDをバックアップ先として準備する

StorageGRIDをバックアップ先として使用する場合は、 https://docs.netapp.com/us-en/storagegrid-117/index.html["StorageGRIDドキュメント"^] StorageGRIDの詳細については、こちらをご覧ください。



[[prepare-aws-to-become-a-backup-destination]]
=== AWSをバックアップ先として準備する

* AWS にアカウントを設定します。
* 設定 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS 権限"^]AWS で。


コンソールでAWSストレージを管理する方法の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["Amazon S3バケットを管理する"^] 。



[[prepare-azure-to-become-a-backup-destination]]
=== Azure をバックアップ先として準備する

* Azure でアカウントを設定します。
* 設定 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Azure のアクセス許可"^]Azure で。


コンソールでAzureストレージを管理する方法の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["Azure ストレージ アカウントを管理する"^] 。



[[set-up-the-netapp-console]]
== NetApp Consoleをセットアップする

次のステップは、NetApp Console と NetApp Ransomware Resilience を設定することです。

レビュー https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["標準モードのコンソール要件"^]。



[[create-a-console-agent]]
=== コンソールエージェントを作成する

NetAppの営業担当者にお問い合わせいただき、このサービスをお試しいただくか、ご利用ください。さらに、Console エージェントには、Ransomware Resilience に必要な機能が含まれています。

NetApp Ransomware Resilience 用の Console エージェントを作成するには、Console エージェントを作成する権限を持つ Console 組織管理者に連絡し、 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["コンソールエージェントを作成する方法"^]を参照してください。


NOTE: コンソールエージェントが複数ある場合、NetApp Ransomware Resilienceは、コンソールに現在表示されているエージェントだけでなく、すべてのコンソールエージェントのデータをスキャンします。このサービスは、組織に関連付けられているすべてのプロジェクトとコンソールエージェントのデータをスキャンします。
