---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: 環境、ネットワーク アクセス、ログイン、Web ブラウザーのサポートを確認して、 NetApp Ransomware Resilienceを開始してください。 
---
= NetApp Ransomware Resilienceの前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
運用環境、ネットワーク アクセス、Web ブラウザの準備状況を確認して、 NetApp Ransomware Resilienceを開始してください。

Ransomware Resilience を使用するには、前提条件を満たしていることを確認してください。



== サポートされているシステム

サポートされているシステムを使用していることを確認してください。

|===
| 環境 | プロトコル | サポート対象のバージョン 


| Amazon FSx for NetApp ONTAP* | CIFS、NFS、SAN | 該当なし 


| Azure NetApp Files | CIFSとNFS | 該当なし 


.2+| Cloud Volumes ONTAP for AWS | CIFSとNFS | 9.11.1以降 


| SAN（FC、iSCSI、NVMe） | 9.17.1以降 


.2+| Google Cloud Platform 向けCloud Volumes ONTAP | CIFSとNFS | 9.11.1以降 


| SAN（FC、iSCSI、NVMe） | 9.17.1以降 


.2+| Microsoft Azure 向けCloud Volumes ONTAP | CIFSとNFS | 9.12.1以降 


| SAN（FC、iSCSI、NVMe） | 9.17.1以降 


.2+| ONTAP （オンプレミス） | CIFSとNFS | 9.11.1以降 


| SAN（FC、iSCSI、NVMe） | 9.17.1以降 
|===
{アスタリスク} Amazon FSx for NetApp ONTAP は、 ARP/AI ではなく、Autonomous Ransomware Protection (ARP) を使用します。違いの詳細については、link:https://docs.netapp.com/us-en/ontap/anti-ransomware/#arp-ai["ARP/AI"^] 。



== NetApp Consoleの要件

NetApp Consoleの構成には次のものが必要です。

* リソースを検出するための組織管理者権限を持つNetApp Consoleユーザー アカウント。
* 少なくとも1つのアクティブなコンソールエージェントが接続しているコンソール組織とシステムlink:concept-ransomware-resilience.html#supported-backup-targets-systems-and-workload-data-sources["サポートされているシステム"]。
+
** オンプレミスのONTAPクラスタまたはAWSまたはAzureクラウドのCloud Volumes ONTAPがコンソールで設定されていない場合は、link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["コンソールエージェントの設定方法を学ぶ"^]そしてlink:https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["標準コンソール要件"^]。
+

NOTE: 単一のコンソール組織に複数のコンソール エージェントがある場合、Ransomware Resilience は、コンソール UI で現在選択されているエージェント以外のすべてのコンソール エージェントにわたってONTAPリソースをスキャンします。



* コンソールエージェントには、 `cloudmanager-ransomware-protection`アクティブな状態のコンテナ。
* NetAppオンプレミスONTAPクラスターまたは AWS または Azure のCloud Volumes ONTAP を備えた少なくとも 1 つのコンソール システム。  Ransomware Resilience は、NAS (NFS および SMB) と SAN (iSCSI、FC、NVMe) の両方のプロトコルをサポートします。
+
** ランサムウェア耐性は、 ONTAPバージョン 9.11.1 以降のONTAPまたはCloud Volumes ONTAPクラスターでサポートされます。
+

NOTE: SAN ワークロードで Ransomware Resilience を使用するには、 ONTAP 9.17.1 以降を実行している必要があります。







== ONTAPの要件

* オンプレミスのONTAPインスタンスでONTAP One ライセンスが有効になっているONTAP 9.11.1 以降を実行している必要があります。  ONTAPサポートの詳細については、以下を参照してください。link:https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["自律型ランサムウェア対策 - 概要"^] 。
* 保護構成（自律型ランサムウェア保護の有効化など）を適用するには、Ransomware Resilience にONTAPクラスターに対する管理者権限が必要です。ONTAPクラスタは、 ONTAPクラスタ管理者のユーザー認証情報のみを使用してオンボードされている必要があります。



NOTE: 管理者以外の認証情報を使用してONTAPクラスターをコンソールに接続している場合は、[ ONTAPクラスター内の認証情報を更新する必要があります](#ontap システム内の非管理者ユーザー権限の更新)。



== データのバックアップ

* 適切なアクセス権限が設定されたバックアップ ターゲット用のNetApp StorageGRID、AWS S3、Azure Blob、または Google Cloud Platform のアカウント。
+
参照 https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["AWS、Azure、またはS3の権限リスト"^]詳細については。

* システムでNetApp Backup and Recovery を有効にする必要はありません。
+
Ransomware Resilience は、設定オプションを通じてバックアップの保存先を構成するのに役立ちます。見るlink:rp-use-settings.html["設定を構成する"] 。





== 疑わしいユーザー行動の要件

Ransomware Resilienceが疑わしいユーザー行動に関するアラートを提供するには、ユーザーアクティビティエージェントを設定する必要があります。ユーザーアクティビティエージェントをインストールするには、システムがlink:reference-user-activity-requirements.html["要件"]を満たしていることを確認してください。



== ONTAPシステムで管理者以外のユーザーの権限を更新する

特定のシステムの管理者以外のユーザー権限を更新する必要がある場合は、この手順の手順を使用します。

. コンソールにログインします。ダッシュボードで、ONTAP ユーザ権限の更新が必要なシステムを特定します。
. システムを選択して詳細を表示します。
. ユーザー名を表示するには、[*追加情報を表示*] を選択します。
. 管理者ユーザーとしてONTAPクラスタ CLI にログインします。
. そのユーザーの既存のロールを表示します：
+
[listing]
----
security login show -user-or-group-name <username>
----
. ユーザーの役割を変更します。入力：
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. Ransomware Resilience を使用するには、 NetApp Consoleに戻ります。

