---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: NetApp Ransomware Resilienceに関するよくある質問への回答をご覧ください。 
---
= NetApp Ransomware Resilience に関するFAQ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
この FAQ は、NetApp Ransomware Resilienceに関する質問への簡単な回答を探している場合に役立ちます。



== 導入

.Ransomware Resilience を使用するにはライセンスが必要ですか?
次のライセンス タイプを使用できます。

* 30 日間の無料トライアルにサインアップしてください。
* Amazon Web Services (AWS) Marketplace、Google Cloud Marketplace、Microsoft Azure Marketplace で、 NetApp Intelligent Servicesおよび Ransomware Resilience の従量課金制 (PAYGO) サブスクリプションを購入します。
* BYOL (お客様独自のライセンス使用) は、 NetApp の営業担当者から取得したNetAppライセンス ファイル (NLF) です。ライセンス シリアル番号を使用して、コンソールのLicenses and subscriptionsセクションで BYOL をアクティブ化できます。


.ランサムウェア耐性をどのように有効にするのですか?
NetApp Consoleから Ransomware Resilience にアクセスできます。必ず link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["アクセスロール"] そして link:rp-start-prerequisites.html["前提条件"]。コンソールエージェントの設定に成功したら、 link:rp-start-discover.html["ワークロードを発見する"]。

詳細については、link:rp-start-login.html["ランサムウェア耐性にアクセス"]そしてlink:rp-start-quick-start.html["ランサムウェア耐性クイックスタートガイド"]。

.Ransomware Resilience は、標準モード、制限モード、プライベート モードで使用できますか?
ランサムウェア耐性は現在、標準モードでのみ利用可能です。

NetAppデータサービス全体にわたるこれらのモードの説明については、 https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["NetApp Consoleの展開モード"^] 。

.Ransomware Resilience の請求はどのように行われますか？
Ransomware Resilience を 30 日間無料でお試しいただけます。NetApp は、Ransomware Resilience の試用版の使用に対して料金を請求しません。

バックアップとリカバリとランサムウェア耐性の両方をお持ちの場合、両方の製品で保護されている共通データについては、ランサムウェア耐性に対してのみ課金されます。

ワークロードが保護対象として分類されると、購入済みの容量または従量課金制のサブスクリプションに対してカウントされます。Ransomware Resilienceは、少なくとも1つのスナップショットまたはバックアップポリシーで検出ポリシーが有効になっている場合、ワークロードを保護されていると分類します。検出ポリシーによって検出されたワークロードのうち、バックアップポリシーやスナップショットポリシーが設定されていないワークロードは、リスクがあると分類されます。リスクのあるワークロードは、購入済みの容量にはカウントされません。

保護されたワークロードは、無料試用期間の終了後、購入した容量またはサブスクリプションに対してカウントされます。ランサムウェア耐性は、効率化前の保護されたワークロードに関連するデータ（ONTAPによって報告される）に対してGB単位で課金されます。

サイジングを検討する際、ライセンス費用はアクティブ ファイル システムの論理容量に基づいて決定されます（つまり、スナップショットが消費する容量は含まれません）。



== アクセス

.ランサムウェア耐性 URL とは何ですか?
ブラウザで次のように入力します https://console.netapp.com/["https://console.netapp.com/ransomware-resilience"^] コンソールにアクセスします。

.アクセス権限はどのように処理されますか?
https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスのコンソールアクセスロールについて学習します"^]。ランサムウェア耐性には link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-ransomware-roles.html["専用アクセスロール"^]。

.どのデバイスの解像度が最適ですか?
Ransomware Resilience に推奨されるデバイス解像度は 1920x1080 以上です。

.どのブラウザを使用すればよいですか?
最新の Web ブラウザを使用してNetApp Consoleにアクセスできます。



== 相互運用性

.Ransomware Resilience はONTAPの保護設定を認識しますか?
はい、Ransomware Resilience はONTAPで設定されたスナップショット スケジュールを検出します。

.ランサムウェア耐性はNetApp Backup and Recoveryとどのように相互作用しますか？
Ransomware Resilience は、Backup and Recovery と連携して、ファイル共有ワークロードのスナップショットおよびバックアップポリシーを検出して設定します。Ransomware Resilience は、Backup and Recovery と連携して、ファイルおよびワークロードの一貫性のあるリカバリを実行します。

ライセンスと課金に関しては、バックアップとリカバリ用の個別のライセンスがない場合でも、Ransomware Resilience をバックアップとリカバリと統合できます。バックアップとリカバリとランサムウェア耐性の両方をお持ちの場合、両方の製品で保護されている共通データについては、ランサムウェア耐性に対してのみ課金されます。



== ワークロード

.ランサムウェア耐性の観点から見たワークロードとは何ですか?
ワークロードは、アプリケーション、VM、またはファイル共有です。ワークロードには、単一のアプリケーション インスタンスによって使用されるすべてのボリュームが含まれます。

たとえば、ora3.host.comにデプロイされたOracleデータベースを考えてみましょう。 `vol1` データを含み、 `vol2` ログを含みます。2 つのボリュームが、その Oracle データベース インスタンスのワークロードを構成します。

.Ransomware Resilience はワークロード データをどのように優先順位付けしますか?
ワークロードの優先度 (クリティカル、標準、重要) は、ワークロードに関連付けられた各ボリュームにすでに適用されているスナップショット頻度とスケジュールされたバックアップによって決まります。

link:rp-use-protect.html["作業負荷の優先度や重要性について知る"] 。

.Ransomware Resilience はどのようなワークロードをサポートしますか?
Ransomware Resilience は、Oracle、ファイル共有、ブロック ストレージ、VM、VM データストアなどのワークロードを識別できます。

.データをワークロードにどのように関連付けますか?
Ransomware Resilience はボリュームとファイル拡張子を検出し、適切なワークロードに関連付けます。

.保護されたワークロードとは何ですか?
ランサムウェア耐性では、主要な検出ポリシーが有効になっているワークロードは「保護」ステータスを表示します。これは、 link:concept-ransomware-resilience.html["自律型ランサムウェア対策（ARP）"] ワークロードに関連するすべてのボリュームで有効になります。

.「リスクのある」ワークロードとは何ですか?
ワークロードでプライマリ検出ポリシーが有効になっていない場合、バックアップとスナップショット ポリシーが有効になっていても、「危険」というラベルが付けられます。ランサムウェア対策として、 link:rp-use-protect.html#add-a-ransomware-protection-strategy["検出ポリシー"]。

.新しいボリュームを追加しましたが、まだ表示されません。どうすればいいですか？
環境に新しいボリュームを追加した場合は、ワークロードの検出を再度開始します。巻物が発見された後、 link:rp-use-protect.html#add-a-ransomware-protection-strategy["新しいボリュームを保護するために保護ポリシーを適用する"]。



== 保護ポリシー

.Ransomware Resilience ランサムウェア ポリシーは、他の種類のワークロード ポリシーと共存しますか?
現在、バックアップとリカバリ (クラウド バックアップ) では、ボリュームごとに 1 つのバックアップ ポリシーがサポートされています。バックアップとリカバリを使用してバックアップ保護を構成すると、バックアップ ポリシーが Ransomware Resilience と共有されます。

スナップショット コピーには制限がなく、各サービスから個別に追加できます。

.ランサムウェア保護戦略にはどのようなポリシーが必要ですか?
あ link:rp-use-protect.html#add-a-ransomware-protection-strategy["ランサムウェア対策戦略"] 必要：

* ランサムウェア検出ポリシー、および
* スナップショットポリシー


ランサムウェア耐性戦略では、バックアップ ポリシーは必要ありません。

.Ransomware Resilience はONTAPの保護設定を認識しますか?
はい、Ransomware Resilienceは、ONTAPで設定されたスナップショットスケジュールを検出します。また、検出されたワークロード内のすべてのボリュームでARPとFPolicyが有効になっているかどうかも検出します。Ransomware Resilienceダッシュボードに表示される情報は、他のNetAppソリューションと製品から集約されたものです。

.ランサムウェア耐性は、NetApp Backup and Recoveryですでに作成されたポリシーを認識しますか？
はい、Backup and Recoveryで管理されているワークロードがある場合、それらの製品によって管理されているポリシーはRansomware Resilienceに取り込まれます。

.NetApp Backup and Recoveryから引き継いだポリシーを変更できますか？
いいえ、Ransomware ResilienceからNetApp Backup and Recoveryで管理されているポリシーを変更することはできません。これらのポリシーへの変更は、NetApp Backup and Recoveryで管理します。

.ONTAPからのポリシー (ARP、FPolicy、スナップショットなど) が存在する場合、それらは Ransomware Resilience で変更されますか?
いいえ。Ransomware Resilience は、 ONTAPの既存の検出ポリシー (ARP、FPolicy 設定) を変更しません。

.Ransomware Resilience にサインアップした後、 NetApp Backup and Recovery に新しいポリシーを追加するとどうなりますか？
ランサムウェア耐性は、NetApp Backup and Recoveryで新しく作成されたポリシーとポリシーの変更を認識します。

.ONTAPからポリシーを変更できますか?
はい、Ransomware Resilience のONTAPからポリシーを変更できます。 Ransomware Resilience で新しいポリシーを作成し、ワークロードに適用することもできます。このアクションにより、既存のONTAPポリシーが Ransomware Resilience で作成されたポリシーに置き換えられます。

.ONTAPでポリシーを無効にできますか?
ONTAPの System Manager UI、API、または CLI を使用して、検出ポリシーで ARP を無効にすることができます。

FPolicy およびバックアップ ポリシーを無効にするには、それらを含まない別のポリシーを適用します。
