---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: NetApp Ransomware Resilience に関するよくある質問への回答をご覧ください。 
---
= NetAppランサムウェア耐性に関するよくある質問
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
この FAQ は、 NetApp Ransomware Resilience に関する質問への簡単な回答を探している場合に役立ちます。



== 導入

*Ransomware Resilience を使用するにはライセンスが必要ですか?*

次のライセンス タイプを使用できます。

* 30 日間の無料トライアルにサインアップしてください。
* Amazon Web Services (AWS) Marketplace、Google Cloud Marketplace、Microsoft Azure Marketplace で、 NetApp Intelligent Services および Ransomware Resilience の従量課金制 (PAYGO) サブスクリプションを購入します。
* BYOL (Bring Your Own License) は、 NetApp の営業担当者から取得したNetAppライセンス ファイル (NLF) です。ライセンス シリアル番号を使用して、コンソールのライセンスとサブスクリプション セクションで BYOL をアクティブ化できます。


*ランサムウェア耐性を有効にするにはどうすればいいですか?*ランサムウェア耐性には有効化は必要ありません。  NetAppコンソールから Ransomware Resilience にアクセスできます。

開始するには、サインアップするか、 NetApp の営業担当者に連絡してこのサービスを試す必要があります。その後、コンソール エージェントを使用すると、ランサムウェア耐性のための適切な機能が含まれるようになります。

Ransomware Resilience を開始するには、最初のランディング ページから [ワークロードの検出を開始する] を選択します。

*Ransomware Resilience は、標準モード、制限モード、プライベートモードで利用できますか?*現時点では、ランサムウェア耐性は標準モードでのみ利用可能です。今後もご期待ください。

NetAppデータサービス全体にわたるこれらのモードの説明については、 https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["NetAppコンソールの展開モード"^] 。



== アクセス

*ランサムウェア耐性 URL とは何ですか?*ブラウザで次のように入力します https://console.netapp.com/["https://console.netapp.com/ransomware-resilience"^]コンソールにアクセスします。

*アクセス権限はどのように処理されますか?*https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["すべてのサービスのコンソールアクセスロールについて学習します"^] 。

*どのデバイスの解像度が最適ですか?*Ransomware Resilience に推奨されるデバイス解像度は 1920x1080 以上です。

*どのブラウザを使用すればよいですか?*任意の最新ブラウザ。



== 他のサービスとのやり取り

*Ransomware Resilience はNetApp ONTAPで行われた保護設定を認識しますか?*はい、Ransomware Resilience はONTAPで設定されたスナップショット スケジュールを検出します。

*Ransomware Resilience を使用してポリシーを設定した場合、今後の変更はこのサービスでのみ行う必要がありますか?*ランサムウェア耐性からポリシーの変更を行うことをお勧めします。

*Ransomware Resilience は、 NetApp Backup and Recovery およびSnapCenterとどのように連携しますか?*

Ransomware Resilience では、次の製品とサービスを使用します。

* ファイル共有ワークロードのスナップショットとバックアップ ポリシーを検出して設定するためのバックアップとリカバリ
* SnapCenterまたはSnapCenter for VMware を使用して、アプリケーションおよび VM ワークロードのスナップショットおよびバックアップ ポリシーを検出し、設定します。


さらに、Ransomware Resilience は、バックアップとリカバリ、およびSnapCenter / SnapCenter for VMware を使用して、ファイルとワークロードの整合性のあるリカバリを実行します。



== ワークロード

*作業負荷を構成するものは何ですか?*ワークロードは、アプリケーション、VM、またはファイル共有です。ワークロードには、単一のアプリケーション インスタンスによって使用されるすべてのボリュームが含まれます。たとえば、ora3.host.com にデプロイされた Oracle DB インスタンスには、データとログ用にそれぞれ vol1 と vol2 を設定できます。これらのボリュームが組み合わさって、Oracle DB インスタンスの特定のインスタンスのワークロードを構成します。

*ランサムウェア耐性はワークロードデータをどのように優先順位付けしますか?*データの優先順位は、作成されたスナップショットのコピーとスケジュールされたバックアップによって決まります。

ワークロードの優先度 (クリティカル、標準、重要) は、ワークロードに関連付けられた各ボリュームにすでに適用されているスナップショット頻度によって決まります。

link:rp-use-protect.html["作業負荷の優先度や重要性について知る"] 。

*Ransomware Resilience はどのようなワークロードをサポートしますか?*

Ransomware Resilience は、Oracle、MySQL、ファイル共有、ブロック ストレージ、VM、VM データストアなどのワークロードを識別できます。

さらに、 SnapCenterまたはSnapCenter for VMware を使用している場合は、これらの製品でサポートされているすべてのワークロードも Ransomware Resilience で識別され、Ransomware Resilience はワークロードの一貫性を保ちながらこれらを保護および回復できます。

*データとワークロードをどのように関連付けますか?*

ランサムウェア耐性は、次の方法でデータをワークロードに関連付けます。

* Ransomware Resilience はボリュームとファイル拡張子を検出し、適切なワークロードに関連付けます。
* さらに、 SnapCenterまたはSnapCenter for VMware があり、バックアップとリカバリでワークロードを構成している場合、Ransomware Resilience は、 SnapCenterおよびSnapCenter for VMware によって管理されているワークロードとそれらに関連付けられたボリュームを検出します。


*「保護された」ワークロードとは何ですか?*ランサムウェア耐性では、プライマリ検出ポリシーが有効になっている場合、ワークロードは「保護」ステータスを表示します。現時点では、これはワークロードに関連するすべてのボリュームで ARP が有効になっていることを意味します。

*「リスクのある」ワークロードとは何ですか?*ワークロードでプライマリ検出ポリシーが有効になっていない場合、バックアップおよびスナップショット ポリシーが有効になっていても、ワークロードは「危険にさらされている」状態になります。

*新しいボリュームが追加されましたが、まだ表示されません* 環境に新しいボリュームを追加した場合は、検出を再度開始し、保護ポリシーを適用してその新しいボリュームを保護します。



== 保護ポリシー

*Ransomware Resilience ランサムウェア ポリシーは、他の種類のワークロード ポリシーと共存しますか?*現在、バックアップとリカバリ (クラウド バックアップ) では、ボリュームごとに 1 つのバックアップ ポリシーがサポートされています。したがって、バックアップとリカバリとランサムウェア耐性はバックアップ ポリシーを共有します。

スナップショット コピーには制限がなく、各サービスから個別に追加できます。

*ランサムウェア保護戦略にはどのようなポリシーが必要ですか?*

ランサムウェア保護戦略には次のポリシーが必要です。

* ランサムウェア検出ポリシー
* スナップショットポリシー


ランサムウェア耐性戦略では、バックアップ ポリシーは必要ありません。

*Ransomware Resilience はNetApp ONTAPで行われた保護設定を認識しますか?*

はい、Ransomware Resilience は、 ONTAPで設定されたスナップショット スケジュールと、検出されたワークロード内のすべてのボリュームで ARP と FPolicy が有効になっているかどうかを検出します。ダッシュボードに最初に表示される情報は、他のNetAppソリューションおよび製品から集約されたものです。

*ランサムウェア耐性は、バックアップとリカバリおよびSnapCenterですでに作成されているポリシーを認識しますか?*

はい、Backup and Recovery またはSnapCenterで管理されているワークロードがある場合、それらの製品によって管理されているポリシーは Ransomware Resilience に取り込まれます。

* NetApp Backup and Recovery やSnapCenterから引き継がれたポリシーを変更できますか?*

いいえ、Ransomware Resilience から Backup and Recovery またはSnapCenterによって管理されるポリシーを変更することはできません。これらのポリシーに対する変更は、Backup and Recovery またはSnapCenterで管理します。

* ONTAPからのポリシーが存在する場合 (ARP、FPolicy、スナップショットなど、System Manager ですでに有効になっている)、それらは Ransomware Resilience で変更されますか? *

いいえ。Ransomware Resilience は、 ONTAPの既存の検出ポリシー (ARP、FPolicy 設定) を変更しません。

*Ransomware Resilience にサインアップした後、Backup and Recovery またはSnapCenterに新しいポリシーを追加するとどうなりますか?*

Ransomware Resilience は、Backup and Recovery またはSnapCenterで作成された新しいポリシーを認識します。

* ONTAPからポリシーを変更できますか?*

はい、Ransomware Resilience のONTAPからポリシーを変更できます。 Ransomware Resilience で新しいポリシーを作成し、ワークロードに適用することもできます。このアクションにより、既存のONTAPポリシーが Ransomware Resilience で作成されたポリシーに置き換えられます。

*ポリシーを無効にできますか?*

System Manager UI、API、または CLI を使用して、検出ポリシーで ARP を無効にすることができます。

FPolicy およびバックアップ ポリシーを無効にするには、それらを含まない別のポリシーを適用します。
