---
sidebar: sidebar 
permalink: task-automate-user-activity.html 
keywords: data breach detection, data breach, user activity, automated response 
summary: NetApp Ransomware Resilienceは、ユーザーアクティビティイベントへの自動応答の作成をサポートしており、スナップショットの自動作成やユーザーのブロックを自動的に実行できます。 
---
= NetApp Ransomware Resilienceにおけるユーザーアクティビティアラートへの対応を自動化します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Ransomware Resilience は、link:concept-user-behavior.html["ユーザーアクティビティイベント"]への自動応答の作成をサポートします。自動応答機能により、Ransomware Resilience は攻撃や警告が検出された際にスナップショットを作成したり、ユーザーをブロックしたりすることができ、ランサムウェアの事象に対してより迅速な対応が可能になります。

暗号化（ユーザーの行動）、データ漏洩、およびデータ破壊イベントに対して、自動応答がサポートされています。自動応答を作成する前に、link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#create-a-user-activity-agent["ユーザーアクティビティエージェントを設定し、ユーザーアクティビティ検出を含むポリシーを有効にし、ユーザーディレクトリコネクタを作成しました"]が必要です。



[[create-an-automated-response]]
== 自動応答を作成する

不審なユーザー行動検出ポリシーで保護されているワークロードが少なくとも1つ存在するストレージVMは、1つしか保護できません。


NOTE: 不審なユーザー行動に対する自動応答では、スナップショットしか取得できません。不審なユーザー行動に対する自動的な対応として、ユーザーをブロックすることはサポートされていません。

.手順
. ランサムウェア耐性で、[**設定**] を選択します。
. ユーザーアクティビティ監視タイルで、**管理**を選択します。
. 「自動応答」タブを選択します。
. 動作を作成するには、**追加**を選択します。
. 自動応答の**名前**を入力してください。
. 応答をトリガーするイベントの種類を選択してください：**攻撃**または**警告**。さまざまな link:rp-use-alert.html#alert-types-and-statuses["アラートの種類"] の詳細をご確認ください。
. 回答を選択してください：
+
** **ユーザーアクセスをブロック**：アラートがトリガーされると、ユーザーは Ransomware Resilience によって保護されているすべてのストレージ VM へのアクセスをブロックされます。
+
このオプションを選択する場合は、ブロックの期間も選択する必要があります。間隔は1時間から24時間の間、または永続的に設定することができます。

** **スナップショットを作成する**：影響を受けるワークロードのスナップショットを作成し、復旧時に使用します。スナップショットは7日間保存されます。


. 自動応答をトリガーするアラートの種類を選択してください：
+
|===


| アラートの種類 | 説明 


| 暗号化（ユーザーの動作） | ランサムウェア耐性機能は、特定のユーザーによって実行された異常なファイルの読み取り、書き込み、および名前変更アクティビティを特定します。 


| データ侵害 | NetApp Ransomware Resilienceは、特定のユーザーによって実行された異常なファイル読み取りアクセスパターンを検出します。 


| データ破壊 | NetApp Ransomware Resilienceは、特定のユーザーによるファイルの大量削除を検出します。 


| 疑わしいユーザー行動 | Ransomware Resilienceは、データ侵害、データ破壊、暗号化の範囲を超える異常な動作を特定します。 
|===
. 自動応答を適用するストレージVMを選択してください。
. 自動応答を作成するには、**追加**を選択します。




[[modify-an-automated-response]]
== 自動応答を変更する

自動応答を作成した後、応答を一時停止、再開、または変更できます。応答の名前、応答をトリガーするアラートの種類、ストレージVM、および実行されるアクションを変更できます。

.手順
. ランサムウェア耐性で、[**設定**] を選択します。
. ユーザーアクティビティ監視タイルで、**管理**を選択します。
. 「自動応答」タブを選択します。
. 変更する自動応答を選択します。
. 応答を一時停止または削除するには、アクションメニューを選択し、**一時停止**（または**開始**）または**削除**を選択します。
+
回答を変更するには、**編集**を選択してください。

. アラートの深刻度以外の設定はすべて変更できます。
. 変更内容を保存するには、**保存**を選択してください。

