---
sidebar: sidebar 
permalink: task-users-manage.html 
keywords: user activity detection, 
summary: NetApp Ransomware Resilienceでユーザーディレクトリコネクタを作成した後、ユーザーのブロックとブロック解除、アラート対象からのユーザー除外が可能です。 
---
= NetApp Ransomware Resilienceにおけるユーザーのブロックとアラートの管理
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Ransomware Resilienceでユーザー ディレクトリ コネクターを作成した後は、ランサムウェア イベントが発生してそれらを評価する際に、ユーザーをブロックおよびブロック解除できます。また、ユーザーの操作が攻撃ではないと確信できる場合は、そのユーザーをランサムウェア アラートから選択的に除外することもできます。

ユーザーをブロックするには、link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#create-a-user-activity-agent["ユーザーアクティビティエージェントを設定し、ユーザーアクティビティ検出を含むポリシーを有効にし、ユーザーディレクトリコネクタを作成しました"]が必要です。


TIP: ユーザーアクティビティ検出イベントにlink:task-automate-user-activity.html["応答を自動化する"]ことができます。



== ブロックされたユーザーを管理する

悪意のある行為に関与していると思われるユーザーをブロックすることができます。

.ユーザーをブロックする
. ランサムウェア耐性で、[**設定**] を選択します。
. 設定ダッシュボードで、「ユーザーアクティビティ監視」タイルを見つけて、**管理**を選択します。
. **ユーザー**タブを選択します。
. 「ユーザーをブロック」を選択します。
. ブロック期間を選択してください。1時間から24時間、または永久ブロックが可能です。
. ブロックするユーザーの名前の横にあるチェックボックスを選択してください。
. **ブロック**を選択します。


.ブロックされたユーザーリストを変更する
. ランサムウェア耐性で、[**設定**] を選択します。
. 設定ダッシュボードで、「ユーザーアクティビティ監視」タイルを見つけて、**管理**を選択します。
. **ユーザー**タブを選択します。
. **ユーザーブロックの編集**を選択します。
. 変更を選択してください。ブロック期間を変更するには、「**ブロック対象ユーザーの期間**」を選択し、期間を変更します。ブロックされたユーザーリストからユーザーを削除するには、「**ユーザーのブロックを解除**」を選択してください。
. ステータスを変更したいブロック済みユーザーの名前の横にあるチェックボックスを選択してください。
. **保存**を選択します。




== ユーザーアラートを管理する

特定の信頼できるユーザーの行動によってユーザー行動アラートがトリガーされる可能性がある場合は、そのユーザーをアラートから除外できます。

.アラートからユーザーを除外する
. ランサムウェア耐性で、[**設定**] を選択します。
. 設定ダッシュボードで、「ユーザーアクティビティ監視」タイルを見つけて、**管理**を選択します。
. **監視対象から除外**タブを選択します。
. UI で個々のユーザーを確認するには、**手動で選択**を選択します。除外されたユーザーのリストをアップロードするには、**アップロード**を選択します。
+
.. **手動で選択**を選択した場合は、除外する特定のユーザーの名前の横にあるチェックボックスをオンにします。
.. **Upload** を選択した場合は、すべてのユーザーのリストが含まれる CSV または JSON ファイルをダウンロードします。リストにアクセスするには、**Download** を選択します。
+
ローカルマシンでファイルを確認します。検出を維持するすべてのユーザーの名前を削除します。検出から除外するユーザーの名前のみがリストに含まれたら、保存します。

+
Ransomware Resilienceで、**Upload**を選択します。ファイルを見つけてアップロードします。



. **追加**を選択して、ユーザーを除外リストへの追加を完了します。
. **監視対象から除外**タブに、ユーザー行動検出アラートから削除されたユーザーの名前がダッシュボードに表示されるようになりました。



TIP: アラートからユーザーを直接除外することもできます。詳細については、link:rp-use-alert.html["ランサムウェアの警告に応答する"]を参照してください。

.除外ユーザーリストからユーザーを削除する
. 設定ダッシュボードで、「ユーザーアクティビティ監視」タイルを見つけて、**管理**を選択します。
. **監視対象から除外**タブを選択します。
. **追加**を選択します。
. 個々のユーザーをUIから除外するには、**手動で選択**を選択してください。
. 除外ユーザーリストから削除するユーザーの名前を見つけます。ユーザー名の行のアクションメニュー（(`...`）を選択し、**削除**をクリックします。
. ダイアログで、**削除**を選択して、選択したユーザーを削除することを確認します。




== 次の手順

* link:task-automate-user-activity.html["ユーザーアクティビティ検出イベントへの応答を自動化する"]

