= データ分類を有効にし、個人を特定できる情報 (PII) をスキャンします
:allow-uri-read: 




=== データ分類を有効にし、個人を特定できる情報 (PII) をスキャンします

このリリースでは、 BlueXPファミリーのコア コンポーネントであるBlueXP classificationを有効にして、ファイル共有ワークロード内のデータをスキャンおよび分類できます。データを分類すると、データに個人情報やプライベートな情報が含まれているかどうかを識別するのに役立ち、セキュリティ リスクが増大する可能性があります。このプロセスはワークロードの重要性にも影響を及ぼし、適切なレベルの保護でワークロードを保護していることを確認するのに役立ちます。

BlueXP ransomware protectionにおける PII データのスキャンは、 BlueXP classificationを導入したお客様には一般にご利用いただけます。  BlueXP classificationはBlueXPプラットフォームの一部として追加料金なしで利用でき、オンプレミスまたは顧客のクラウドに展開できます。

参照 https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-settings.html["BlueXP ransomware protection設定を構成する"]。

スキャンを開始するには、[保護] ページで、[プライバシーの露出] 列の [*露出を特定*] をクリックします。

https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect-classify.html["BlueXP classificationで個人を特定できる機密データをスキャン"] 。



=== Microsoft Sentinel との SIEM 統合

Microsoft Sentinel を使用して脅威の分析と検出を行うために、データをセキュリティおよびイベント管理システム (SIEM) に送信できるようになりました。以前は、SIEM として AWS Security Hub または Splunk Cloud を選択できました。

https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-settings.html["BlueXP ransomware protection設定の構成について詳しくは、こちらをご覧ください。"] 。



=== 今すぐ30日間無料トライアル

このリリースでは、 BlueXP ransomware protectionの新規導入に 30 日間の無料トライアルが提供されます。以前は、 BlueXP ransomware protectionは90 日間の無料トライアルを提供していました。すでに 90 日間の無料トライアル中の場合は、そのオファーは 90 日間継続されます。



=== Podman のファイルレベルでアプリケーション ワークロードを復元する

アプリケーション ワークロードをファイル レベルで復元する前に、攻撃の影響を受けた可能性のあるファイルの一覧を表示し、復元するファイルを特定できるようになりました。以前は、組織 (以前のアカウント) 内のBlueXPコネクタが Podman を使用していた場合、この機能は無効になっていました。  Podman で有効になりました。  BlueXP ransomware protectionで復元するファイルを選択したり、アラートの影響を受けたすべてのファイルをリストした CSV ファイルをアップロードしたり、復元するファイルを手動で特定したりすることができます。

https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-recover.html["ランサムウェア攻撃からの回復について詳しくはこちら"] 。
