= Digital Advisorによるセキュリティリスク評価
:allow-uri-read: 




[[security-risk-assessment-from-digital-advisor]]
=== Digital Advisorによるセキュリティリスク評価

BlueXP ランサムウェア対策は、NetApp Digital Advisor からクラスターの高リスクおよび重大なセキュリティリスクに関する情報を収集します。リスクが検出された場合、BlueXP ランサムウェア対策はダッシュボードの「推奨されるアクション」ペインに次の推奨事項を表示します：「クラスター <name> の既知のセキュリティ脆弱性を修正する」ダッシュボードの推奨事項から「確認して修正する」を選択し、Digital Advisor および関連する共通脆弱性識別子（CVE）の記事を確認します。セキュリティリスクが複数ある場合は、Digital Advisor で詳細を確認してください。

参照 https://docs.netapp.com/us-en/active-iq/index.html["Digital Advisorのドキュメント"^]。



[[back-up-to-google-cloud-platform]]
=== Google Cloud Platform へのバックアップ

このリリースでは、バックアップ先を Google Cloud Platform バケットに設定できます。以前は、バックアップ先を追加できるのはNetApp StorageGRID、Amazon Web Services、Microsoft Azure のみでした。

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-backup-destination.html["BlueXP ransomware protection設定の構成について詳しくは、こちらをご覧ください。"]。



[[support-for-google-cloud-platform]]
=== Google Cloud Platform のサポート

このサービスでは、ストレージ保護のために、Google Cloud Platform 用のCloud Volumes ONTAP をサポートするようになりました。以前は、このサービスはオンプレミスの NAS に加えて、Amazon Web Services および Microsoft Azure 向けのCloud Volumes ONTAPのみをサポートしていました。

https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["BlueXP ransomware protectionとサポートされているデータソース、バックアップ先、作業環境について学びます"] 。



[[role-based-access-control]]
=== ロールベース アクセス制御

ロールベースのアクセス制御 (RBAC) を使用して、特定のアクティビティへのアクセスを制限できるようになりました。  BlueXP ransomware protectionでは、 BlueXPの 2 つのロール ( BlueXPアカウント管理者と非アカウント管理者 (閲覧者)) を使用します。

各ロールが実行できるアクションの詳細については、 https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["ロールベースのアクセス制御権限"] 。
