= SANワークロードのサポート
:allow-uri-read: 




=== SANワークロードのサポート

このリリースには、BlueXP ransomware protectionにおける SAN ワークロードのサポートが含まれています。NFS および CIFS ワークロードに加えて、SAN ワークロードも保護できるようになりました。

詳細については、 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-prerequisites.html["BlueXP ransomware protectionの前提条件"] 。



=== ワークロード保護の改善

このリリースでは、NetAppの他のツール（BlueXPバックアップとリカバリなど）のスナップショットポリシーやバックアップポリシーを使用したワークロードの設定プロセスが改善されました。以前のリリースでは、BlueXPランサムウェア対策は他のツールからのポリシーを検出し、検出ポリシーの変更のみを許可していました。このリリースでは、スナップショットポリシーとバックアップポリシーをBlueXPランサムウェア対策ポリシーに置き換えるか、他のツールのポリシーを引き続き使用できるようになりました。

詳細については、link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["ワークロードを保護する"] 。



=== メール通知

BlueXP ransomware protectionが攻撃の可能性を検出すると、 BlueXP通知に通知が表示され、設定した電子メール アドレスに電子メールが送信されます。

電子メールには、重大度、影響を受けるワークロード、 BlueXP ransomware protectionの *アラート* タブのアラートへのリンクに関する情報が含まれています。

BlueXP ransomware protectionでセキュリティおよびイベント管理 (SIEM) システムを構成した場合、サービスはアラートの詳細を SIEM システムに送信します。

詳細については、link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["検出されたランサムウェアアラートを処理する"] 。
